# Generated by Django 4.2.17 on 2025-01-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=150)),
                ('date_posted', models.DateTimeField()),
                ('hidden', models.BooleanField()),
                ('date_hidden', models.DateTimeField()),
                ('hidden_by', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
