# Generated by Django 4.2.17 on 2025-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0004_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
