# Generated by Django 4.2.17 on 2025-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0007_alter_post_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Member',
            },
        ),
    ]
