# Generated by Django 4.2.17 on 2025-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0009_alter_member_options_member_joined_date_member_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
